### ISSUE TITLE
我认为不需要安装 net-tools 

### ISSUE THREAD

**Issue by falseUtopia** [rogvc/wslbridge#1]
我认为不需要安装 net-tools  ,因为net-tools可以被 iproute2 代替

```
$remoteport = bash.exe -c "ip addr show dev eth0 | grep 'inet '"
```

**Comment by rogvc** [comment]
Sorry, I don't understand the issue. Could you please write what the problem is in English?

**Comment by falseUtopia** [comment]
兄弟，你翻译一下就明白了😄
